project_id = "peuoyvedpbleoohjaditf"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://peuoyvedpbleoohjaditf.supabase.co"]
jwt_expiry = 3600

[functions.openai-chat]
verify_jwt = false