// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peuoyvedpbleoohjditf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBldW95dmVkcGJsZW9vaGpkaXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjMzMjksImV4cCI6MjA2NzY5OTMyOX0.0v3qzS_daPRoc3sWYy4SurJbRtZ8jQasc9pU5WR1JdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});